{% set name = "inject" %}
{% set version = "5.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f7c305a75cc4e3a331d248e996f25783ba784b88d5a9b9f73c53eacaa6d76985

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - inject
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ivankorobkov/python-inject
  summary: Python dependency injection framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wolfv
